# Generated by Django 5.1.4 on 2026-01-17 13:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=500)),
                ('current_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_location', models.CharField(max_length=500)),
                ('pickup_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_location', models.CharField(max_length=500)),
                ('dropoff_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_cycle_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('total_distance_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_driving_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('route_polyline', models.JSONField(blank=True, default=list)),
                ('schedule', models.JSONField(blank=True, default=list)),
                ('stops', models.JSONField(blank=True, default=list)),
                ('hos_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trip',
                'verbose_name_plural': 'trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
